# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Herts for Refugees
email: contact@timpaul.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/herts-for-refugees" # the subpath of your site, e.g. /blog
url: "https://timpaul.github.io/" # the base hostname & protocol for your site
twitter_username: timpaul
github_username:  timpaul

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock

# Prose.io settings
prose:
  rooturl: '_posts'
  siteurl: 'http://timpaul.github.io/herts-for-refugees/'
  relativeLinks: 'http://timpaul.github.io/herts-for-refugees/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "Title of the blog post goes here"

